// Auto-generated. Replaced Google Drive links with local paths.
export const creatorProfileImages: Record<string, string> = {
  "sherinsbeauty": "/creator-images/Sherin Amara.jpg",
  "ossymarwah": "/creator-images/Ossy Marwah _ اسامة مروة.jpg",
  "alrafaelo": "/creator-images/AL RAFAELO.jpg",
  "cedrabeauty": "/creator-images/Cedra Ammara.jpg",
  "anas_alshayb": "/creator-images/انس الشايب - ANAS ELSHAYIB.jpg",
  "leen_mohd98": "/creator-images/لين محمد _ LEEN MOHD.jpg",
  "lemansheroes": "/creator-images/Benoit Fraylon.jpg",
  "thisisshams": "/creator-images/شمس الفارس _ Shams Faris.jpg",
  "mahmoudmahe.r": "/creator-images/Mahmoud Maher _ محمود ماهر.jpg",
  "elqaq": "/creator-images/Naji Elqaq.jpg",
  "rsbelhasa": "/creator-images/Moneykicks - We Living Life.jpg",
  "_ad_": "/creator-images/Salem Sultan.jpg",
  "matt__org": "/creator-images/Mahdi mehmandoost.jpg",
  "nadina_ioana": "/creator-images/Nadina Ioana.jpg",
  "afrobysara": "/creator-images/The Afrobysara Fam.jpg",
  "rickyelalemancubano": "/creator-images/Ricky Schwarz.jpg",
  "mamoisawi": "/creator-images/محمود العيساوي __ Mahmoud Isawi.jpg",
  "dilya.abdusalimova": "/creator-images/Dilnoza Abdusalimova.jpg",
  "mustafa_mohd9": "/creator-images/Mustafa Mohd.jpg",
  "madmaxdoll": "/creator-images/L’Aura  Dragu.jpg",
  "dr_kasia_sterriker": "/creator-images/Dr Eng. Kasia Sterriker.jpg",
  "rrrayanfahmi": "/creator-images/Rayan 🤍.jpg",
  "twinshadban": "/creator-images/Twins Hadban توينز هضبان.jpg",
  "ilyansaqer": "/creator-images/Ally haki اليان صقر.jpg",
  "elnfard": "/creator-images/Elen NFard.jpg",
  "antonellaattorre": "/creator-images/Antonella Attorre.jpg",
  "karina.kapris": "/creator-images/Karina Kapris 💎 The Art of Femininity.jpg",
  "ali___barberr": "/creator-images/ALi  SABOUHİ.jpg",
  "auda_amar": "/creator-images/Sultan-Beibars.jpg",
  "nada.benkirat": "/creator-images/Nada Benkirat.jpg",
  "majd_alzakout": "/creator-images/Majd Alzakout _ مجد الزاقوت.jpg",
  "elenaelsabbagh": "/creator-images/Elena El Sabbagh-ايلانا الصباغ.jpg",
  "sarahsaamiii": "/creator-images/ساره سامي.jpg",
  "dejiwastaken": "/creator-images/Deji Adebola.jpg",
  "anjablaa": "/creator-images/Anja Blagojevic.jpg",
  "manishbhati777": "/creator-images/Manish Bhati.jpg",
  "lilian_mohd94": "/creator-images/ليليان بركات 🌸 lilian barakat.jpg",
  "sultanalarafati": "/creator-images/Sultan Alarafati.jpg",
  "maya_tarraf": "/creator-images/Maya Tarraf.jpg",
  "alina.ilina": "/creator-images/Alina Ilina.jpg",
  "karim_elrafie": "/creator-images/Karim El-rafie.jpg",
  "sanah_kanafani": "/creator-images/Sanah kanafani Hamdan.jpg",
  "judi.dalati": "/creator-images/جودي دالاتي.jpg",
  "levanbene": "/creator-images/Levan Bene.jpg",
  "sonuha": "/creator-images/Samuel Onuha.jpg",
  "taifour1": "/creator-images/Ali Mohammed Tifour.jpg",
  "sol_een": "/creator-images/Soleen Mohammed.jpg",
  "abiralhady": "/creator-images/Abir Alhady عبير الهادي.jpg",
  "professorcryptoyoutube": "/creator-images/🌏 PROFESSOR CRYPTO ™.jpg",
  "kelly.bortolini": "/creator-images/Kelly Bortolini.jpg",
  "abdullah.alkobeissy1": "/creator-images/Abdullah Al kobeissy.jpg",
  "ayline.ea": "/creator-images/AYLIN ELMA 🦋.jpg",
  "mustafagameover": "/creator-images/Mustafaa Jamal.jpg",
  "ayahsharafdesigns": "/creator-images/Ayah Sharaf_أية شرف.jpg",
  "rabah.hameid": "/creator-images/rabah hameid.jpg",
  "adnan.yabroudi": "/creator-images/Adnan Yabroudi.jpg",
  "sedra_samerr": "/creator-images/سيدرا سامر💖.jpg",
  "dadocesaro": "/creator-images/Davide Cesaro • Monaco.jpg",
  "chahnasoni": "/creator-images/Chahna چاہنا.jpg",
  "alsharif.x": "/creator-images/Kareem Al Sharif.jpg",
  "lovers_wave": "/creator-images/Lovers 💞.jpg",
  "1ahmad": "/creator-images/Ahmad Mahmood.jpg",
  "that_hungrybelly": "/creator-images/Thasneem Thaj.jpg",
  "youssefelabiad_": "/creator-images/Youssef Elabiad.jpg",
  "varda.rz": "/creator-images/Varda Rizvi.jpg",
  "asraralarfeen": "/creator-images/𝗠𝗼𝗵𝗮𝗺𝗲𝗱 𝗔𝗹𝗶 𝗢𝗳𝗳𝗶𝗰𝗶𝗮𝗹.jpg",
  "taranettz": "/creator-images/Mahsad ziaee.jpg",
  "itz3amer": "/creator-images/Amer Mohamad - عامر محمد.jpg",
  "fattal.fadi": "/creator-images/Fadi Fattal _ فادي فتال.jpg",
  "jibberwithjaber": "/creator-images/Jibber with Jaber podcast.jpg",
  "amaralbawab": "/creator-images/Amar Al Bawab عمار البواب.jpg",
  "habiba.elhady": "/creator-images/Habiba El-hady  حبيبه الهآدى.jpg",
  "barretjay_": "/creator-images/Jay Grai Barret.jpg",
  "khalifatasweq": "/creator-images/Ahmed Khalifa أحمد خليفة.jpg",
  "official_s1": "/creator-images/𝐒𝟏.jpg",
  "riamaryroy": "/creator-images/Ria Mary Roy.jpg",
  "mizteriously": "/creator-images/Mizna Arshad.jpg",
  "nour_awad.life": "/creator-images/Nour Awad.jpg",
  "talal_s_adaileh": "/creator-images/Talal Sameer Adaileh.jpg",
  "official.tamer": "/creator-images/Tamer Suleiman.jpg",
  "yassrab": "/creator-images/Yasser Abdal Rahman.jpg",
  "miss_valeriaradchenko": "/creator-images/Валерия.jpg",
  "melissamouzannar": "/creator-images/Melissa Mouzannar.jpg",
  "searina": "/creator-images/Searina Abdel Kader سيرينا عبدالقادر.jpg",
  "iamstipke": "/creator-images/Dejan Stipke Stipić.jpg",
  "placesandfaces_800": "/creator-images/Sam Gattani.jpg",
  "salma_asmi": "/creator-images/Dilnoza Abdusalimova.jpg",
  "aichouchaoulhyane1": "/creator-images/عيشوشة🌸.jpg",
  "nastaran__shayanfar2018": "/creator-images/nastaranshayanfar.jpg",
  "cheb.handi.officiel": "/creator-images/Cheb Handi Officiel.jpg",
  "nawarofficial2": "/creator-images/Nawar Fawaz.jpg",
  "hhenrywells": "/creator-images/Henry Wells.jpg",
  "estephany_gutierre": "/creator-images/Estephany Gutiérrez.jpg",
  "asiyeekarakus": "/creator-images/Asiye Topçu Karakuş.jpg",
  "zylkcr": "/creator-images/Zeynel KAÇAR.jpg"
};

export function getCreatorProfileImage(username: string): string | undefined {
  return creatorProfileImages[username];
}
